### ISSUE TITLE
Panic: interface conversion: interface {} is int, not float64

### ISSUE THREAD

**Issue by john-kacino** [elvis972602/Kemono-scraper#2]
I follow the instruction to create config.yaml as below, and put it in the same directory with exe file. 

The error message comes when I am trying to run it. It works fine if I input in command line.

Also switches --extensionOnly and --extensionExcept in README.MD are incorrect. The program only recognizes --extension-only and --extension-except. This takes me much time to understand where the problem is after reading error log.

Moreover, when I try to download large PSD files, it always ends like `[31m[Failed][0mcontext deadline exceeded` and files are broken. Take a try at https://kemono.party/fanbox/user/273185/post/5358600

```
retry: 10
retry-interval: 30
with-prefix-number: true
```

```
panic: interface conversion: interface {} is int, not float64

goroutine 1 [running]:
main.setFlag()
	C:/Users/elvis/GolandProjects/colly/Kemono-scraper-latest/main/main.go:549 +0x1179
main.main()
	C:/Users/elvis/GolandProjects/colly/Kemono-scraper-latest/main/main.go:55 +0x9f
```

**Comment by elvis972602** [comment]
Thank you for reporting the issue. 

I have resolved the interface conversion error and updated the README.md and added type checking to ensure that it can accept both int and float. 

The issue with downloading PSD files, it may be caused by the file size exceeding the default timeout of HTTP requests, which is 5 minutes. To solve this issue, I have adjusted the default timeout to 30 minutes. Additionally, you can also adjust the timeout by setting the `download-timeout` parameter.

Thanks again for your feedback!
