### ISSUE TITLE
Bug: Try to download a link 

### ISSUE THREAD

**Issue by MVPAIR** [elvis972602/Kemono-scraper#23]
![image](https://github.com/elvis972602/Kemono-scraper/assets/98071184/ab592202-4724-488f-a8ad-f734ce520248)
![image](https://github.com/elvis972602/Kemono-scraper/assets/98071184/b02d4174-2f71-4c80-a7c4-457331e6b7ae)

**Comment by MVPAIR** [comment]
is there a way to download these embeded link into a txt file?

**Comment by elvis972602** [comment]
This seems to be caused by a long name, because it uses a URL instead of a normal file name.
Normally, the external link, the dropbox in this post will not appear in the attachments, but in the content as in the link above. 
It seems to show up a lot in this author's posts, I think one could try filtering non-kemono site URL sources to prevent downloading it.

**Comment by elvis972602** [comment]
> is there a way to download the links embeded in Files section into a txt file or merge them with the Content file ?

You can use content option to download content with embedded links as html,  
```
content: true
```
