### ISSUE TITLE
kemono现在打不开？

### ISSUE THREAD

**Issue by qq734628996** [elvis972602/Kemono-scraper#7]

**Comment by elvis972602** [comment]
Hi, I am able to open it normally at the moment. 
Perhaps you could provide a more specific URL or situation. You could also try using a browser to see if the inability to access is due to network factors.
### Issue with the Kemono website itself
I am powerless to help, you can only wait for it to be repaired.  
### Network issue 
You could try connecting via a VPN or proxy.   
  
If it's an issue with the application, I welcome you to provide more detailed information. I will respond to you as soon as possible
